name: Run reproducer
on: workflow_dispatch
jobs:
  gradle-macos-test1:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test1' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-ubuntu-test1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test1' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-windows-test1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test1' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-macos-test2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test2' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-ubuntu-test2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test2' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-windows-test2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test2' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-macos-test3:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test3' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-ubuntu-test3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test3' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  gradle-windows-test3:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --tests 'IOTest.test3' -i --debug --stacktrace --no-daemon --no-build-cache --no-configuration-cache --rerun-tasks
  maven-all-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Use maven
      run: mvn test
